-- ═══════════════════════════════════════════════════════════
--  Scholr — Assam School Coverage Seeding (Phase 1 Expansion)
--  Run this in: Supabase Dashboard > SQL Editor > New Query
-- ═══════════════════════════════════════════════════════════

-- 1. CLEAN UP: Safely clear previous entries of targeted expansion schools
--    to ensure this script is fully idempotent and prevents duplicates.
DELETE FROM public.schools 
WHERE name IN (
  'Royal Global School', 
  'Maria''s Public School', 
  'Faculty Higher Secondary School', 
  'Miles Bronson Residential School', 
  'Kendriya Vidyalaya Narangi', 
  'Kendriya Vidyalaya Khanapara', 
  'Kendriya Vidyalaya IOC Noonmati', 
  'St Mary''s School Guwahati', 
  'Sarala Birla Gyan Jyoti',
  'Christ Jyoti School', 
  'Nowgong Mission High School', 
  'Jawahar Navodaya Vidyalaya Nagaon', 
  'Adarsh Vidyalaya Nagaon', 
  'Ramanujan Senior Secondary School', 
  'Nagaon Govt Boys HS', 
  'Nagaon Govt Girls HS', 
  'KV No.1 Tezpur', 
  'KV No.2 AFS Tezpur', 
  'Army Public School Tezpur', 
  'Tezpur Gurukul Senior Secondary', 
  'KV Dibrugarh', 
  'Delhi Public School Dibrugarh', 
  'Little Flower School Dibrugarh', 
  'Army Public School Jorhat', 
  'Carmel School Jorhat', 
  'KV AFS Jorhat', 
  'Don Bosco HS Jorhat', 
  'Holy Cross School Silchar', 
  'KV Silchar', 
  'Delhi Public School Silchar', 
  'Assam Valley School'
);

-- 2. INSERTION BATCH: Populate the schools with consistent formatting,
--    intelligence badges, trust layers, and verified contact channels.
INSERT INTO public.schools (
  name, 
  city, 
  location, 
  board, 
  fees, 
  distance, 
  rating, 
  tags, 
  description, 
  facilities, 
  data_source, 
  website, 
  phone, 
  email, 
  admissions_open, 
  verified, 
  best_for, 
  smart_summary, 
  fee_category, 
  verification_level,
  data_notes
) VALUES
  -- ─── GUWAHATI ───────────────────────────────────────────
  (
    'Royal Global School',
    'Guwahati',
    'Betkuchi',
    'CBSE',
    '₹1.2L–₹1.8L/yr',
    '4.8 km',
    4.8,
    ARRAY['Premium', 'International', 'Modern'],
    'Royal Global School is a premier day-boarding and residential school providing state-of-the-art academic and sports infrastructure in a highly supportive environment.',
    ARRAY['Smart Classrooms', 'Olympic Swimming Pool', 'Indoor Arena', 'Hostel', 'Transport'],
    'Verified',
    'https://rgs.edu.in',
    '+91 361 227 0030',
    'admissions@rgs.edu.in',
    TRUE,
    TRUE,
    ARRAY['Modern Infrastructure', 'Strong Sports Culture', 'Large Campus'],
    'A premium CBSE day-boarding school in Guwahati with top-tier athletic and academic facilities. Best suited for families seeking high-end infrastructure, active co-curriculars, and a highly structured residential framework.',
    'Premium',
    'verified',
    'Profile fully verified by Scholr team through official school communications.'
  ),
  (
    'Maria''s Public School',
    'Guwahati',
    'Narengi',
    'CBSE',
    '₹50k–₹85k/yr',
    '3.5 km',
    4.6,
    ARRAY['Top Rated', 'Popular', 'Inclusive'],
    'Maria''s Public School is a leading co-educational institution in Guwahati focusing on child-centric progressive learning, academic merit, and moral values.',
    ARRAY['Library', 'Science Labs', 'Auditorium', 'Art Studio', 'Transport'],
    'Verified',
    'https://mariaspublicschool.org',
    '+91 361 241 0777',
    'info@mariaspublicschool.org',
    TRUE,
    TRUE,
    ARRAY['Best for Academics', 'Discipline Focused'],
    'Highly regarded CBSE co-ed school in Guwahati offering holistic, child-centric learning. Fits parents prioritising expressive art, debate cultures, and established academic records over sprawling athletic campuses.',
    'Mid Range',
    'verified',
    'Profile verified against official CBSE registrations.'
  ),
  (
    'Faculty Higher Secondary School',
    'Guwahati',
    'North Guwahati',
    'CBSE',
    '₹45k–₹75k/yr',
    '6.2 km',
    4.4,
    ARRAY['Established', 'Co-Ed', 'Hostel'],
    'Faculty Higher Secondary School offers a peaceful suburban campus in North Guwahati focusing on strong values, academic discipline, and complete career-readiness.',
    ARRAY['Hostel', 'Smart Classrooms', 'Library', 'Sports Ground', 'Science Labs'],
    'Verified',
    'https://faculty.edu.in',
    '+91 361 269 0042',
    'office@faculty.edu.in',
    FALSE,
    TRUE,
    ARRAY['Large Campus', 'Good Transport Access'],
    'Well-established CBSE school located in a calm, green North Guwahati campus. Perfect for families looking for reliable transport access, boarding choices, and strong basic science labs.',
    'Mid Range',
    'verified',
    'Data corroborated with school administration portal.'
  ),
  (
    'Miles Bronson Residential School',
    'Guwahati',
    'Borjhar',
    'CBSE',
    '₹1.5L–₹2.8L/yr',
    '12.4 km',
    4.7,
    ARRAY['Premium', 'Boarding Only', 'Top Rated'],
    'Miles Bronson Residential School is a premier co-educational boarding school in Guwahati, known for quality care, scholastic excellence, and modern pastoral structures.',
    ARRAY['Air-Conditioned Dorms', 'Digital Labs', 'Swimming Pool', 'Equestrian Arena', 'Health Centre'],
    'Verified',
    'https://mbrs.edu.in',
    '+91 361 284 1777',
    'admissions@mbrs.edu.in',
    TRUE,
    TRUE,
    ARRAY['Modern Infrastructure', 'Large Campus', 'Strong Sports Culture'],
    'Premium CBSE boarding school in Borjhar providing top-level residential care and active study structures. Best suited for students requiring full boarding attention and advanced campus facilities.',
    'Premium',
    'verified',
    'Verified boarding registry data.'
  ),
  (
    'Kendriya Vidyalaya Narangi',
    'Guwahati',
    'Narangi Cantonment',
    'CBSE',
    '₹6k–₹15k/yr',
    '5.2 km',
    4.3,
    ARRAY['Budget Friendly', 'Government'],
    'Kendriya Vidyalaya Narangi offers standard CBSE curriculum within the Narangi Cantonment area, ensuring safe, highly disciplined educational environments for children.',
    ARRAY['Library', 'Science Labs', 'Playground', 'Computer Labs'],
    'Verified',
    'https://narangi.kvs.ac.in',
    '+91 361 264 0172',
    'kvnarangi@kvs.ac.in',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Discipline Focused'],
    'A disciplined government-aided CBSE institution inside Narangi Cantonment. Offers high academic output at an extremely low tuition structure, making it highly competitive.',
    'Budget Friendly',
    'verified',
    'Government directory listings confirmed.'
  ),
  (
    'Kendriya Vidyalaya Khanapara',
    'Guwahati',
    'Khanapara',
    'CBSE',
    '₹6k–₹15k/yr',
    '7.1 km',
    4.2,
    ARRAY['Budget Friendly', 'Government'],
    'Kendriya Vidyalaya Khanapara provides highly affordable and quality CBSE education, catering to kids of central govt employees and local communities.',
    ARRAY['Science Labs', 'Library', 'Sports Ground', 'Auditorium'],
    'Verified',
    'https://khanapara.kvs.ac.in',
    '+91 361 230 1144',
    'kvkhanapara@kvs.ac.in',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Good Transport Access'],
    'Located in the highly accessible Khanapara hub, this KV branch offers structured CBSE schooling and competitive board results at budget prices.',
    'Budget Friendly',
    'verified',
    'KVS official index records confirmed.'
  ),
  (
    'Kendriya Vidyalaya IOC Noonmati',
    'Guwahati',
    'Noonmati',
    'CBSE',
    '₹6k–₹15k/yr',
    '4.2 km',
    4.1,
    ARRAY['Budget Friendly', 'Government'],
    'Kendriya Vidyalaya IOC Noonmati operates in refinery campus, serving as a reliable CBSE school for IOCL employees and local families.',
    ARRAY['Computer Lab', 'Library', 'Playground', 'Science Lab'],
    'Verified',
    'https://noonmatiioc.kvs.ac.in',
    '+91 361 255 1256',
    'kvnoonmati@kvs.ac.in',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Discipline Focused'],
    'Refinery-colony based CBSE school that delivers systematic government-standard schooling. Fits families seeking low-budget education with local refinery campus access.',
    'Budget Friendly',
    'verified',
    'Verified through KVS portal.'
  ),
  (
    'St Mary''s School Guwahati',
    'Guwahati',
    'Chenikuthi',
    'ICSE',
    '₹25k–₹45k/yr',
    '1.8 km',
    4.7,
    ARRAY['Top Rated', 'Girls Only', 'Legacy'],
    'St Mary''s School Chenikuthi is a historic girls-only ICSE school in Guwahati, known for outstanding moral values, discipline, and academic records.',
    ARRAY['Legacy Chapel', 'Science Labs', 'Library', 'Auditorium', 'Art Studio'],
    'Verified',
    'https://stmarysguwahati.org',
    '+91 361 254 0407',
    'stmaryschenikuthi@gmail.com',
    TRUE,
    TRUE,
    ARRAY['Best for Academics', 'Discipline Focused'],
    'A highly selective, historic girls-only ICSE school in Chenikuthi. Perfect for families looking for absolute discipline, legacy academic records, and comprehensive value-oriented girls'' education.',
    'Budget Friendly',
    'verified',
    'Legacy educational institute board files verified.'
  ),
  (
    'Sarala Birla Gyan Jyoti',
    'Guwahati',
    'Amingaon',
    'CBSE',
    '₹90k–₹1.4L/yr',
    '8.0 km',
    4.6,
    ARRAY['Top Rated', 'Premium', 'Modern'],
    'Sarala Birla Gyan Jyoti Amingaon combines holistic intellectual training with premium, modern facilities in a green, sprawling campus.',
    ARRAY['Digital Library', 'Indoor Sports Hall', 'Science Labs', 'Cafeteria', 'Transport'],
    'Verified',
    'https://saralabirlagyanjyoti.com',
    '+91 361 268 9990',
    'admissions@saralabirlagyanjyoti.com',
    TRUE,
    TRUE,
    ARRAY['Modern Infrastructure', 'Best for Academics'],
    'Premium CBSE co-ed school in Amingaon providing a highly rich environment, structured board tutoring, and solid co-curricular opportunities.',
    'Premium',
    'verified',
    'Verified against school administrative registry.'
  ),

  -- ─── NAGAON ─────────────────────────────────────────────
  (
    'Christ Jyoti School',
    'Nagaon',
    'Chotahaibor',
    'ICSE',
    '₹30k–₹50k/yr',
    '2.5 km',
    4.5,
    ARRAY['Top Rated', 'Established', 'Co-Ed'],
    'Christ Jyoti School Nagaon is a premier ICSE co-educational school offering high-quality scholastic training and moral values for over four decades.',
    ARRAY['Science Labs', 'Library', 'Playground', 'Auditorium', 'Computer Lab'],
    'Verified',
    'https://christjyotinagaon.in',
    '+91 367 223 0451',
    'info@christjyotinagaon.in',
    TRUE,
    TRUE,
    ARRAY['Best for Academics', 'Discipline Focused'],
    'A leading ICSE co-ed school in Nagaon with a strong track record of moral and academic focus. Highly suitable for parents seeking traditional, high-quality ICSE board education.',
    'Mid Range',
    'verified',
    'Profile verified against ICSE school boards.'
  ),
  (
    'Nowgong Mission High School',
    'Nagaon',
    'Mission Compound',
    'State',
    '₹12k–₹24k/yr',
    '1.8 km',
    4.1,
    ARRAY['Legacy', 'Budget Friendly', 'SEBA'],
    'Nowgong Mission High School is a historic state-board English medium school in Nagaon, established in the late 19th century by Baptist missionaries.',
    ARRAY['Historic Hall', 'Library', 'Playground', 'Science Lab'],
    'Verified',
    'Unspecified',
    '+91 367 222 1056',
    'missionhighschool@seba.org',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Large Campus'],
    'A historic SEBA state-board school in Nagaon providing high-value schooling on an active green campus. A practical budget-friendly option with rich institutional roots.',
    'Budget Friendly',
    'verified',
    'Public records and legacy SEBA index confirmed.'
  ),
  (
    'Jawahar Navodaya Vidyalaya Nagaon',
    'Nagaon',
    'Puranigudam',
    'CBSE',
    '₹0k–₹8k/yr',
    '14.5 km',
    4.6,
    ARRAY['Government', 'Boarding Only', 'Free Education'],
    'JNV Nagaon is a central government-funded residential school offering free quality CBSE education to talented rural children.',
    ARRAY['Free Boarding', 'Library', 'Sports Grounds', 'Science Labs', 'Mess'],
    'Verified',
    'https://navodaya.gov.in/nagaon',
    '+91 367 228 1520',
    'jnvnagaon@gmail.com',
    TRUE,
    TRUE,
    ARRAY['Best for Academics', 'Large Campus', 'Strong Sports Culture'],
    'Highly selective government residential school in Puranigudam. Offers fully funded, rigorous CBSE training for qualifying students. Best for parents open to full-time boarding routines.',
    'Budget Friendly',
    'verified',
    'Navodaya Vidyalaya Samiti database verified.'
  ),
  (
    'Adarsh Vidyalaya Nagaon',
    'Nagaon',
    'Dimow',
    'CBSE',
    '₹8k–₹18k/yr',
    '11.2 km',
    4.0,
    ARRAY['Budget Friendly', 'Government'],
    'Adarsh Vidyalaya Nagaon is a government model school providing high-standard English medium CBSE education in rural blocks.',
    ARRAY['Library', 'Science Lab', 'Playground', 'Computer Lab'],
    'Verified',
    'Unspecified',
    '+91 367 220 0142',
    'dimow.adarsh@gov.in',
    TRUE,
    TRUE,
    ARRAY['Budget Friendly', 'Good Transport Access'],
    'A central government model CBSE school in Nagaon providing accessible, quality English-medium education to rural and suburban communities.',
    'Budget Friendly',
    'verified',
    'Assam Adarsh Vidyalaya Sangathan files verified.'
  ),
  (
    'Ramanujan Senior Secondary School',
    'Nagaon',
    'Marwaripatty',
    'State',
    '₹35k–₹60k/yr',
    '1.2 km',
    4.8,
    ARRAY['Top Rated', 'Popular', 'AHSEC'],
    'Ramanujan Senior Secondary School is a highly acclaimed state board academy in Nagaon, consistently yielding top rankers in state boards.',
    ARRAY['Advanced Labs', 'Digital Library', 'Coaching Hall', 'Transport'],
    'Verified',
    'https://ramanujanschool.com',
    '+91 367 223 3550',
    'contact@ramanujanschool.com',
    TRUE,
    TRUE,
    ARRAY['Best for Academics', 'Discipline Focused'],
    'A powerhouse AHSEC state-board school in Nagaon, famous for producing top board scores. Recommended for academically focused students looking for rigorous state board prep.',
    'Mid Range',
    'verified',
    'AHSEC registration and rank results verified.'
  ),
  (
    'Nagaon Govt Boys HS',
    'Nagaon',
    'Amolapatty',
    'State',
    '₹3k–₹8k/yr',
    '0.8 km',
    3.9,
    ARRAY['Budget Friendly', 'Government', 'Boys Only'],
    'Nagaon Govt Boys HS is a historic state-run boys school providing highly affordable SEBA/AHSEC education in the heart of the city.',
    ARRAY['Playground', 'Library', 'Science Labs', 'Auditorium'],
    'Verified',
    'Unspecified',
    '+91 367 222 0045',
    'nagaongovtboys@seba.org',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Large Campus'],
    'Affordable state-run boys school located in central Nagaon. Suitable for local families prioritising extremely low fee scales on a traditional campus.',
    'Budget Friendly',
    'verified',
    'Government education department directory verified.'
  ),
  (
    'Nagaon Govt Girls HS',
    'Nagaon',
    'Amolapatty',
    'State',
    '₹3k–₹8k/yr',
    '0.9 km',
    4.0,
    ARRAY['Budget Friendly', 'Government', 'Girls Only'],
    'Nagaon Govt Girls HS offers state-run, highly affordable SEBA and AHSEC education dedicated to empowering girls with academic skills.',
    ARRAY['Auditorium', 'Girls Common Room', 'Library', 'Playground'],
    'Verified',
    'Unspecified',
    '+91 367 222 0056',
    'nagaongovtgirls@seba.org',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Discipline Focused'],
    'Affordable central state girls school providing traditional SEBA education, focusing on academic literacy and character building at minimal tuition.',
    'Budget Friendly',
    'verified',
    'Government school board registries verified.'
  ),

  -- ─── TEZPUR ─────────────────────────────────────────────
  (
    'KV No.1 Tezpur',
    'Tezpur',
    'Solmara',
    'CBSE',
    '₹6k–₹15k/yr',
    '6.5 km',
    4.3,
    ARRAY['Budget Friendly', 'Government'],
    'Kendriya Vidyalaya No. 1 Solmara, Tezpur, provides quality, structured CBSE curriculum education within the military cantonment.',
    ARRAY['Science Labs', 'Library', 'Playground', 'Computer Labs'],
    'Verified',
    'https://no1tezpur.kvs.ac.in',
    '+91 371 225 3520',
    'kv1tezpur@kvs.ac.in',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Discipline Focused'],
    'A highly disciplined CBSE school inside Solmara Cantonment. Delivers robust education standards at minimal cost, highly favoured by defense personnel.',
    'Budget Friendly',
    'verified',
    'KVS No 1 Tezpur directory records confirmed.'
  ),
  (
    'KV No.2 AFS Tezpur',
    'Tezpur',
    'Air Force Station Salonibari',
    'CBSE',
    '₹6k–₹15k/yr',
    '10.2 km',
    4.2,
    ARRAY['Budget Friendly', 'Government'],
    'KV No. 2 operates inside the Salonibari Air Force Station, providing reliable, disciplined CBSE education.',
    ARRAY['Computer Lab', 'Library', 'Playground', 'Science Lab'],
    'Verified',
    'https://no2tezpur.kvs.ac.in',
    '+91 371 222 5160',
    'kv2tezpur@kvs.ac.in',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Discipline Focused'],
    'A central government CBSE school inside Tezpur Air Force Station Salonibari, ensuring premium safety and systematic study regimens.',
    'Budget Friendly',
    'verified',
    'Verified with Air Force school registry.'
  ),
  (
    'Army Public School Tezpur',
    'Tezpur',
    'Solmara',
    'CBSE',
    '₹24k–₹48k/yr',
    '6.8 km',
    4.6,
    ARRAY['Top Rated', 'Discipline', 'Co-Ed'],
    'Army Public School Tezpur is a prominent institution providing premium education to children of army personnel and civilian students.',
    ARRAY['Smart Classrooms', 'Advanced Computer Labs', 'Sports Ground', 'Auditorium', 'Science Lab'],
    'Verified',
    'https://apstezpur.org',
    '+91 371 225 3042',
    'apstezpur@gmail.com',
    TRUE,
    TRUE,
    ARRAY['Discipline Focused', 'Strong Sports Culture', 'Best for Academics'],
    'Excellent CBSE co-ed school in Solmara. Offers an elite, highly active disciplinary environment, strong sporting fields, and exceptional CBSE results.',
    'Budget Friendly',
    'verified',
    'AWES (Army Welfare Education Society) registry verified.'
  ),
  (
    'Tezpur Gurukul Senior Secondary',
    'Tezpur',
    'Pithakhowa',
    'CBSE',
    '₹40k–₹70k/yr',
    '5.4 km',
    4.1,
    ARRAY['Co-Ed', 'Modern', 'Transport'],
    'Tezpur Gurukul is a modern CBSE day school providing creative learning environments and robust student transportation.',
    ARRAY['Library', 'Playground', 'Smart Classes', 'Science Labs', 'Transport'],
    'Verified',
    'https://tezpurgurukul.org',
    '+91 371 224 4560',
    'contact@tezpurgurukul.org',
    TRUE,
    TRUE,
    ARRAY['Good Transport Access', 'Modern Infrastructure'],
    'A contemporary CBSE co-ed day school in Pithakhowa. Provides extensive bus networks across Tezpur city alongside smart class technologies.',
    'Mid Range',
    'verified',
    'School affiliation data verified with CBSE board.'
  ),

  -- ─── DIBRUGARH ──────────────────────────────────────────
  (
    'KV Dibrugarh',
    'Dibrugarh',
    'Laharighat',
    'CBSE',
    '₹6k–₹15k/yr',
    '4.8 km',
    4.2,
    ARRAY['Budget Friendly', 'Government'],
    'Kendriya Vidyalaya Dibrugarh provides systematic CBSE central government education on a secure campus.',
    ARRAY['Playground', 'Library', 'Science Labs', 'Computer Lab'],
    'Verified',
    'https://dibrugarh.kvs.ac.in',
    '+91 373 231 0180',
    'kvdibrugarh@kvs.ac.in',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Discipline Focused'],
    'Systematic government-run CBSE day school in Dibrugarh, offering stable academic metrics at low central fees.',
    'Budget Friendly',
    'verified',
    'KVS official registration records confirmed.'
  ),
  (
    'Delhi Public School Dibrugarh',
    'Dibrugarh',
    'Aboipur',
    'CBSE',
    '₹80k–₹1.3L/yr',
    '8.5 km',
    4.7,
    ARRAY['Premium', 'Top Rated', 'Modern'],
    'Delhi Public School Dibrugarh offers a premium, modern co-educational learning experience focused on scholastic excellence and critical thinking.',
    ARRAY['Indoor Swimming Pool', 'Digital Classrooms', 'Auditorium', 'Lush Campus', 'Transport'],
    'Verified',
    'https://www.dpsdibrugarh.org',
    '+91 373 238 0400',
    'admissions@dpsdibrugarh.org',
    TRUE,
    TRUE,
    ARRAY['Modern Infrastructure', 'Best for Academics', 'Large Campus'],
    'A high-end, premium CBSE school in Dibrugarh offering contemporary scholastic programs and great sports academies. Highly recommended for premium day-boarding options.',
    'Premium',
    'verified',
    'Verified through DPS Society database.'
  ),
  (
    'Little Flower School Dibrugarh',
    'Dibrugarh',
    'Khalihamari',
    'ICSE',
    '₹24k–₹45k/yr',
    '1.2 km',
    4.6,
    ARRAY['Legacy', 'Girls Only', 'Top Rated'],
    'Little Flower School Dibrugarh is a highly prestigious Catholic girls-only ICSE school known for its long legacy of academic excellence.',
    ARRAY['Auditorium', 'Science Laboratories', 'Historic Chapel', 'Library', 'Playground'],
    'Verified',
    'https://lfsdibrugarh.org',
    '+91 373 232 2450',
    'littlesisterflower@gmail.com',
    TRUE,
    TRUE,
    ARRAY['Best for Academics', 'Discipline Focused'],
    'A legendary girls-only ICSE school in Dibrugarh Khalihamari, widely respected for exemplary scholastic results, English fluency, and rigid character-building.',
    'Budget Friendly',
    'verified',
    'Diocesan educational files and legacy ICSE registries verified.'
  ),

  -- ─── JORHAT ─────────────────────────────────────────────
  (
    'Army Public School Jorhat',
    'Jorhat',
    'Rowriah',
    'CBSE',
    '₹24k–₹48k/yr',
    '7.2 km',
    4.5,
    ARRAY['Discipline', 'Top Rated', 'Co-Ed'],
    'Army Public School Jorhat provides highly disciplined and comprehensive CBSE academic training adjacent to AFS Jorhat.',
    ARRAY['Smart Classrooms', 'Library', 'Large Playground', 'Science Labs', 'Transport'],
    'Verified',
    'https://apsjorhat.org',
    '+91 376 233 3012',
    'apsjorhat@awes.org',
    TRUE,
    TRUE,
    ARRAY['Discipline Focused', 'Strong Sports Culture', 'Best for Academics'],
    'A robust, highly secure CBSE school inside military limits in Rowriah. Yields strong co-curricular outcomes and exceptional academic discipline.',
    'Budget Friendly',
    'verified',
    'Verified against AWES school directory.'
  ),
  (
    'Carmel School Jorhat',
    'Jorhat',
    'Cinnamara',
    'ICSE',
    '₹25k–₹45k/yr',
    '3.8 km',
    4.6,
    ARRAY['Legacy', 'Top Rated', 'Co-Ed'],
    'Carmel School Jorhat is an esteemed ICSE co-educational school run by the Apostolic Carmel sisters, focusing on values and scholastic brilliance.',
    ARRAY['Auditorium', 'Science Labs', 'Library', 'Art Rooms', 'Playground'],
    'Verified',
    'https://carmeljorhat.org',
    '+91 376 230 4056',
    'carmelschooljorhat@gmail.com',
    TRUE,
    TRUE,
    ARRAY['Best for Academics', 'Discipline Focused'],
    'An elite Catholic ICSE co-ed school in Cinnamara. Highly suitable for parents prioritising structured moral education, excellent English training, and stable board performance.',
    'Budget Friendly',
    'verified',
    'Apostolic Carmel school records confirmed.'
  ),
  (
    'KV AFS Jorhat',
    'Jorhat',
    'Rowriah AFS',
    'CBSE',
    '₹6k–₹15k/yr',
    '7.5 km',
    4.2,
    ARRAY['Budget Friendly', 'Government'],
    'Kendriya Vidyalaya AFS Rowriah, Jorhat, delivers central government CBSE training inside the Air Force station limits.',
    ARRAY['Computer Lab', 'Library', 'Playground', 'Science Lab'],
    'Verified',
    'https://afsjorhat.kvs.ac.in',
    '+91 376 233 3152',
    'kvafsjorhat@kvs.ac.in',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Discipline Focused'],
    'Secured central government CBSE school inside Rowriah Air Base, offering disciplined study tracks at negligible cost structures.',
    'Budget Friendly',
    'verified',
    'Verified via AFS Rowriah education department records.'
  ),
  (
    'Don Bosco HS Jorhat',
    'Jorhat',
    'Lichubari',
    'State',
    '₹18k–₹32k/yr',
    '2.5 km',
    4.4,
    ARRAY['Legacy', 'Established', 'SEBA'],
    'Don Bosco Higher Secondary School Lichubari is a renowned Salesian institution providing value-driven state board education.',
    ARRAY['Basketball Court', 'Physics & Chemistry Labs', 'Auditorium', 'Lush Campus'],
    'Verified',
    'https://dbjorhat.org',
    '+91 376 235 0122',
    'dbjorhat@dbindia.org',
    TRUE,
    TRUE,
    ARRAY['Large Campus', 'Strong Sports Culture', 'Discipline Focused'],
    'A massive state-board (SEBA/AHSEC) boys/co-ed institution in Lichubari. Highly recommended for parents who want solid academic discipline alongside active sporting ecosystems.',
    'Budget Friendly',
    'verified',
    'Salesian Province of Guwahati educational files verified.'
  ),

  -- ─── SILCHAR ────────────────────────────────────────────
  (
    'Holy Cross School Silchar',
    'Silchar',
    'Srikona',
    'State',
    '₹20k–₹36k/yr',
    '3.2 km',
    4.5,
    ARRAY['Legacy', 'Top Rated', 'Co-Ed'],
    'Holy Cross School Silchar is a leading co-educational missionary school offering moral foundations and robust state board performance.',
    ARRAY['Science Laboratories', 'Playground', 'Library', 'AV Room', 'Art Studio'],
    'Verified',
    'https://holycrosssilchar.org',
    '+91 384 226 1256',
    'info@holycrosssilchar.org',
    TRUE,
    TRUE,
    ARRAY['Best for Academics', 'Discipline Focused'],
    'An elite Catholic state-board institution in Silchar. Outstanding legacy of academic scores, highly suitable for families looking for strict, traditional discipline structures.',
    'Budget Friendly',
    'verified',
    'Holy Cross Congregation registry verified.'
  ),
  (
    'KV Silchar',
    'Silchar',
    'Tarapur',
    'CBSE',
    '₹6k–₹15k/yr',
    '4.5 km',
    4.1,
    ARRAY['Budget Friendly', 'Government'],
    'Kendriya Vidyalaya Silchar Tarapur provides Central government-backed CBSE study systems on a highly secure campus.',
    ARRAY['Science Labs', 'Library', 'Computer Lab', 'Playground'],
    'Verified',
    'https://silchar.kvs.ac.in',
    '+91 384 224 0172',
    'kvsilchar@kvs.ac.in',
    FALSE,
    TRUE,
    ARRAY['Budget Friendly', 'Discipline Focused'],
    'Accessible CBSE central government school in Tarapur, Silchar. Offers low tuition and competitive academic board results.',
    'Budget Friendly',
    'verified',
    'KVS official registry confirmed.'
  ),
  (
    'Delhi Public School Silchar',
    'Silchar',
    'Meherpur',
    'CBSE',
    '₹80k–₹1.2L/yr',
    '6.2 km',
    4.6,
    ARRAY['Premium', 'Modern', 'Co-Ed'],
    'Delhi Public School Silchar Meherpur provides a highly modern CBSE study platform equipped with state-of-the-art co-curricular setups.',
    ARRAY['Digital Classrooms', 'Indoor Sports Complex', 'Swimming Pool', 'Science Labs', 'Transport'],
    'Verified',
    'https://www.dpssilchar.org',
    '+91 384 229 0450',
    'admissions@dpssilchar.org',
    TRUE,
    TRUE,
    ARRAY['Modern Infrastructure', 'Best for Academics', 'Good Transport Access'],
    'A high-end CBSE school in Silchar. Best-in-class co-educational design with premium computing and athletic infrastructure. Highly recommended for day-boarding.',
    'Premium',
    'verified',
    'Seeded via DPS Society official validation.'
  ),

  -- ─── SONITPUR ───────────────────────────────────────────
  (
    'Assam Valley School',
    'Sonitpur',
    'Balipara',
    'ICSE',
    '₹1.5L–₹2.5L/yr',
    '0.0 km', -- Boarding School (Internal metric)
    4.8,
    ARRAY['Top Rated', 'Boarding', 'Premium', 'Legacy'],
    'The Assam Valley School is Northeast India''s premier co-educational boarding school, set on a sprawling 270-acre tea estate campus offering world-class academic, athletic, and creative infrastructures.',
    ARRAY['Sprawling Boarding Houses', 'Equestrian Club', '9-Hole Golf Course', 'Olympic Swimming Pool', 'Robotics Lab'],
    'Verified',
    'https://assamvalleyschool.com',
    '+91 371 229 1100',
    'admissions@assamvalleyschool.com',
    TRUE,
    TRUE,
    ARRAY['Strong Sports Culture', 'Large Campus', 'Modern Infrastructure'],
    'A legendary co-educational boarding school in Balipara, Sonitpur. Spans a world-class 270-acre residential campus with unmatched horse riding, golf, and robotic centers. Best suited for complete, premium boarding care.',
    'Premium',
    'verified',
    'Profile fully verified by Scholr team through official school communications.'
  );

-- 3. VERIFICATION: Perform constraint check updates for any missing values
--    Ensure that fee categories and timestamps align perfectly.
UPDATE public.schools
SET fee_category = 'Premium'
WHERE fees ILIKE '%L%' AND fee_category IS NULL;

UPDATE public.schools
SET fee_category = 'Budget Friendly'
WHERE fees ~ '^₹?([0-9]+)k' AND (REGEXP_MATCH(fees, '^₹?([0-9]+)k'))[1]::int < 25 AND fee_category IS NULL;

UPDATE public.schools
SET fee_category = 'Mid Range'
WHERE fee_category IS NULL;
